# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4240dd8caf99b1192ab54781e7c0573a8b6eddf2a878fcfe54dabf9d6975961765df8b2160736ac9bea67bab833f1d65f42e7e41565e78131ad8040554d6e0b4

test:
  secret_key_base: 032f4e5260ef186a38fb726cb1a30e5c9ded543b63349fadf791c01d93b2d08ae6cc2bcd6e5b87637f0af174032ff8521464af301a06e97c6e5bf805461719f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
